FROM golang:1.23-alpine

  # Install git
RUN set -ex; \
apk update; \
apk add --no-cache git

  # Set working directory
WORKDIR /go/src/github.com/pennsieve/packages-service

  # Run tests
ENTRYPOINT ["./run-tests.sh"]
