#file: noinspection MaybeTerraformTemplateInspection
openapi: 3.0.1
info:
  version: "3.0"
  title: Package Service
  description: |
    The Package Service handles package related requests
  termsOfService: https://docs.pennsieve.io/page/pennsieve-terms-of-use
  contact:
    name: Pennsieve Support
    email: support@pennsieve.net
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api2.pennsieve.io/packages
    description: Production server
  - url: https://api2.pennsieve.net/packages
    description: Development server
externalDocs:
  description: Find more info here
  url: https://docs.pennsieve.io
tags:
  - name: Packages Service
    description: Management of dataset packages
    externalDocs:
      url: https://docs.pennsieve.io/reference

paths:
  /restore:
    post:
      summary: Restore deleted items
      description: |
        Starts restore process for the given deleted items
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: restoreItems
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
      requestBody:
        description: node ids of the items to restore
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/restoreRequest'
      responses:
        '200':
          description: The result of starting the restore process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restoreResponse'
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Error'

  /cloudfront/sign:
    get:
      summary: Generate CloudFront signed URLs for assets
      description: |
        Authenticated endpoint that generates CloudFront signed URLs for package viewer assets.
        This endpoint validates dataset and package ownership before generating signed URLs.
        Provides better performance and caching compared to direct S3 access.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: cloudfrontSign
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
        - in: query
          name: package_id
          schema:
            type: string
          required: true
          description: package node id
        - in: query
          name: path
          schema:
            type: string
          required: true
          description: path to the viewer asset within the package
      responses:
        '200':
          description: Successfully generated CloudFront signed URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  signed_url:
                    type: string
                    description: The CloudFront signed URL
                  expires_at:
                    type: integer
                    format: int64
                    description: Unix timestamp when the signed URL expires
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/Error'

components:
  x-amazon-apigateway-integrations:
    packages-service:
      type: aws_proxy
      uri: ${packages_service_lambda_arn}
      httpMethod: POST
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT
      payloadFormatVersion: 2.0
  securitySchemes:
    token_dataset_auth:
      type: "apiKey"
      name: "Unused"
      in: "header"
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Authorization,$request.querystring.dataset_id"
        authorizerUri: ${authorize_lambda_invoke_uri}
        authorizerPayloadFormatVersion: "2.0"
        authorizerResultTtlInSeconds: 300
        type: "request"
        enableSimpleResponses: true
        authorizerCredentials: ${gateway_authorizer_role}

  responses:
    Unauthorized:
      description: Incorrect authentication or user has incorrect permissions.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    Error:
      description: Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
  schemas:
    restoreRequest:
      type: object
      properties:
        nodeIds:
          type: array
          items:
            type: string
          description: the node ids of the items to restore
    restoreResponse:
      type: object
      properties:
        success:
          type: array
          items:
            type: string
          description: the node ids for which restore has started
        failures:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              error:
                type: string
          description: any restore failures grouped by node id


