#file: noinspection MaybeTerraformTemplateInspection
openapi: 3.0.1
info:
  version: "3.0"
  title: Package Service
  description: |
    The Package Service handles package related requests
  termsOfService: https://docs.pennsieve.io/page/pennsieve-terms-of-use
  contact:
    name: Pennsieve Support
    email: support@pennsieve.net
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api2.pennsieve.io/packages
    description: Production server
  - url: https://api2.pennsieve.net/packages
    description: Development server
externalDocs:
  description: Find more info here
  url: https://docs.pennsieve.io
tags:
  - name: Packages Service
    description: Management of dataset packages
    externalDocs:
      url: https://docs.pennsieve.io/reference

paths:
  /restore:
    post:
      summary: Restore deleted items
      description: |
        Starts restore process for the given deleted items
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: restoreItems
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
      requestBody:
        description: node ids of the items to restore
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/restoreRequest'
      responses:
        '200':
          description: The result of starting the restore process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restoreResponse'
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Error'

  /presign/s3:
    get:
      summary: Generate presigned URLs for S3 objects
      description: |
        Authenticated endpoint that generates presigned URLs for S3 objects.
        This endpoint validates dataset and package ownership before generating URLs.
        Supports both package files and viewer assets.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: presignS3Get
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
        - in: query
          name: package_id
          schema:
            type: string
          required: true
          description: package node id to fetch from S3
        - in: query
          name: path
          schema:
            type: string
          required: false
          description: optional path for viewer assets within the package
        - in: query
          name: redirect
          schema:
            type: string
            enum: ["true", "false"]
          required: false
          description: whether to return HTTP redirect (default true) or JSON with presigned URL (false)
        - in: header
          name: Range
          schema:
            type: string
          required: false
          description: Range header for partial content requests
      responses:
        '200':
          description: Successful response from S3
          content:
            '*/*':
              schema:
                type: string
                format: binary
        '206':
          description: Partial content response from S3
          content:
            '*/*':
              schema:
                type: string
                format: binary
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Error'
    options:
      summary: CORS preflight for presigned URL generation
      description: |
        Handles OPTIONS preflight requests for CORS support.
        Returns appropriate CORS headers for the presign endpoint.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: presignS3Options
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
        - in: query
          name: package_id
          schema:
            type: string
          required: true
          description: package node id
      responses:
        '204':
          description: Successful CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Max-Age:
              schema:
                type: string
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Error'
    head:
      summary: HEAD request for S3 package file metadata
      description: |
        Authenticated endpoint that generates presigned URLs and retrieves S3 metadata.
        Clients like DuckDB use HEAD requests to get Content-Length before making range requests.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: presignS3Head
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
        - in: query
          name: package_id
          schema:
            type: string
          required: true
          description: package node id to fetch metadata from S3
        - in: query
          name: path
          schema:
            type: string
          required: false
          description: optional path for viewer assets within the package
      responses:
        '200':
          description: Successful HEAD response from S3
          headers:
            Content-Length:
              schema:
                type: string
            Content-Type:
              schema:
                type: string
            ETag:
              schema:
                type: string
            Last-Modified:
              schema:
                type: string
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Error'

  /cloudfront/sign:
    get:
      summary: Generate CloudFront signed URLs for assets
      description: |
        Authenticated endpoint that generates CloudFront signed URLs for package viewer assets.
        This endpoint validates dataset and package ownership before generating signed URLs.
        Provides better performance and caching compared to direct S3 access.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: cloudfrontSign
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
        - in: query
          name: package_id
          schema:
            type: string
          required: true
          description: package node id
        - in: query
          name: path
          schema:
            type: string
          required: true
          description: path to the viewer asset within the package
      responses:
        '200':
          description: Successfully generated CloudFront signed URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  signed_url:
                    type: string
                    description: The CloudFront signed URL
                  expires_at:
                    type: integer
                    format: int64
                    description: Unix timestamp when the signed URL expires
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/Error'
    options:
      summary: CORS preflight for CloudFront signed URL generation
      description: |
        Handles OPTIONS preflight requests for CORS support.
        Returns appropriate CORS headers for the CloudFront signing endpoint.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: cloudfrontSignOptions
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
      responses:
        '204':
          description: Successful CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Max-Age:
              schema:
                type: string
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/Error'

  /proxy/s3:
    get:
      summary: Proxy S3 requests using presigned URLs
      description: |
        Unauthenticated proxy endpoint for S3 requests using presigned URLs.
        This endpoint accepts a presigned URL as input and proxies the request,
        handling CORS requirements for clients like DuckDB that cannot add custom headers.
        GET requests return HTTP redirects to the presigned URL.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: proxyS3Get
      tags:
        - Packages Service
      parameters:
        - in: query
          name: presigned_url
          schema:
            type: string
          required: true
          description: The presigned S3 URL to proxy
      responses:
        '307':
          description: Temporary redirect to the presigned URL
          headers:
            Location:
              schema:
                type: string
            Access-Control-Allow-Origin:
              schema:
                type: string
        '4XX':
          $ref: '#/components/responses/BadRequest'
        '5XX':
          $ref: '#/components/responses/Error'
    options:
      summary: CORS preflight for S3 proxy requests
      description: |
        Handles OPTIONS preflight requests for the unauthenticated proxy endpoint.
        Returns appropriate CORS headers to allow clients to access S3 through the proxy.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: proxyS3Options
      tags:
        - Packages Service
      parameters:
        - in: query
          name: presigned_url
          schema:
            type: string
          required: true
          description: The presigned S3 URL (required for consistency but not used in OPTIONS)
      responses:
        '204':
          description: Successful CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Max-Age:
              schema:
                type: string
        '4XX':
          $ref: '#/components/responses/BadRequest'
        '5XX':
          $ref: '#/components/responses/Error'
    head:
      summary: HEAD request proxy for S3 metadata
      description: |
        Unauthenticated proxy endpoint that forwards HEAD requests to S3 using presigned URLs.
        Returns S3 metadata headers directly (not a redirect) for clients like DuckDB.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: proxyS3Head
      tags:
        - Packages Service
      parameters:
        - in: query
          name: presigned_url
          schema:
            type: string
          required: true
          description: The presigned S3 URL to retrieve metadata from
      responses:
        '200':
          description: Successful HEAD response with S3 metadata
          headers:
            Content-Length:
              schema:
                type: string
            Content-Type:
              schema:
                type: string
            ETag:
              schema:
                type: string
            Last-Modified:
              schema:
                type: string
            Accept-Ranges:
              schema:
                type: string
            Access-Control-Allow-Origin:
              schema:
                type: string
        '4XX':
          $ref: '#/components/responses/BadRequest'
        '5XX':
          $ref: '#/components/responses/Error'

components:
  x-amazon-apigateway-integrations:
    packages-service:
      type: aws_proxy
      uri: ${packages_service_lambda_arn}
      httpMethod: POST
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT
      payloadFormatVersion: 2.0
  securitySchemes:
    token_dataset_auth:
      type: "apiKey"
      name: "Unused"
      in: "header"
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Authorization,$request.querystring.dataset_id"
        authorizerUri: ${authorize_lambda_invoke_uri}
        authorizerPayloadFormatVersion: "2.0"
        authorizerResultTtlInSeconds: 300
        type: "request"
        enableSimpleResponses: true
        authorizerCredentials: ${gateway_authorizer_role}

  responses:
    Unauthorized:
      description: Incorrect authentication or user has incorrect permissions.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    Error:
      description: Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
  schemas:
    restoreRequest:
      type: object
      properties:
        nodeIds:
          type: array
          items:
            type: string
          description: the node ids of the items to restore
    restoreResponse:
      type: object
      properties:
        success:
          type: array
          items:
            type: string
          description: the node ids for which restore has started
        failures:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              error:
                type: string
          description: any restore failures grouped by node id


