#file: noinspection MaybeTerraformTemplateInspection
openapi: 3.0.1
info:
  version: "3.0"
  title: Package Service
  description: |
    The Package Service handles package related requests
  termsOfService: https://docs.pennsieve.io/page/pennsieve-terms-of-use
  contact:
    name: Pennsieve Support
    email: support@pennsieve.net
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://api2.pennsieve.io/packages
    description: Production server
  - url: https://api2.pennsieve.net/packages
    description: Development server
externalDocs:
  description: Find more info here
  url: https://docs.pennsieve.io
tags:
  - name: Packages Service
    description: Management of dataset packages
    externalDocs:
      url: https://docs.pennsieve.io/reference

paths:
  /restore:
    post:
      summary: Restore deleted items
      description: |
        Starts restore process for the given deleted items
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: restoreItems
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
      requestBody:
        description: node ids of the items to restore
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/restoreRequest'
      responses:
        '200':
          description: The result of starting the restore process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/restoreResponse'
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Error'

  /s3/proxy:
    get:
      summary: Proxy for S3 package file requests
      description: |
        Generates presigned URLs and proxies requests to S3 with proper CORS handling.
        This endpoint handles GET requests for package files and returns appropriate CORS headers
        for clients that require OPTIONS preflight support (e.g., DuckDB, web browsers).
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: s3ProxyGet
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
        - in: query
          name: package_id
          schema:
            type: string
          required: true
          description: package node id to fetch from S3
        - in: query
          name: path
          schema:
            type: string
          required: false
          description: optional path for viewer assets within the package
        - in: header
          name: Range
          schema:
            type: string
          required: false
          description: Range header for partial content requests
      responses:
        '200':
          description: Successful response from S3
          content:
            '*/*':
              schema:
                type: string
                format: binary
        '206':
          description: Partial content response from S3
          content:
            '*/*':
              schema:
                type: string
                format: binary
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Error'
    options:
      summary: CORS preflight for S3 package file requests
      description: |
        Handles OPTIONS preflight requests for CORS support.
        Returns appropriate CORS headers to allow clients to access S3 package files.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: s3ProxyOptions
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
        - in: query
          name: package_id
          schema:
            type: string
          required: true
          description: package node id
      responses:
        '204':
          description: Successful CORS preflight response
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Max-Age:
              schema:
                type: string
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Error'
    head:
      summary: HEAD request proxy for S3 package file metadata
      description: |
        Generates presigned URLs and proxies HEAD requests to S3 to retrieve metadata.
        Clients like DuckDB use HEAD requests to get Content-Length before making range requests.
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/packages-service'
      operationId: s3ProxyHead
      security:
        - token_dataset_auth: [ ]
      tags:
        - Packages Service
      parameters:
        - in: query
          name: dataset_id
          schema:
            type: string
          required: true
          description: dataset node id
        - in: query
          name: package_id
          schema:
            type: string
          required: true
          description: package node id to fetch metadata from S3
        - in: query
          name: path
          schema:
            type: string
          required: false
          description: optional path for viewer assets within the package
      responses:
        '200':
          description: Successful HEAD response from S3
          headers:
            Content-Length:
              schema:
                type: string
            Content-Type:
              schema:
                type: string
            ETag:
              schema:
                type: string
            Last-Modified:
              schema:
                type: string
        '4XX':
          $ref: '#/components/responses/Unauthorized'
        '5XX':
          $ref: '#/components/responses/Error'

components:
  x-amazon-apigateway-integrations:
    packages-service:
      type: aws_proxy
      uri: ${packages_service_lambda_arn}
      httpMethod: POST
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT
      payloadFormatVersion: 2.0
  securitySchemes:
    token_dataset_auth:
      type: "apiKey"
      name: "Unused"
      in: "header"
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Authorization,$request.querystring.dataset_id"
        authorizerUri: ${authorize_lambda_invoke_uri}
        authorizerPayloadFormatVersion: "2.0"
        authorizerResultTtlInSeconds: 300
        type: "request"
        enableSimpleResponses: true
        authorizerCredentials: ${gateway_authorizer_role}

  responses:
    Unauthorized:
      description: Incorrect authentication or user has incorrect permissions.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
    Error:
      description: Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errorId:
                type: string
  schemas:
    restoreRequest:
      type: object
      properties:
        nodeIds:
          type: array
          items:
            type: string
          description: the node ids of the items to restore
    restoreResponse:
      type: object
      properties:
        success:
          type: array
          items:
            type: string
          description: the node ids for which restore has started
        failures:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              error:
                type: string
          description: any restore failures grouped by node id


